### ISSUE TITLE
Improper behavior of the triangle with a border width greater than 1 

### ISSUE THREAD

**Issue by delexzone** [cliftonm/FlowSharp#2]
## Steps to reproduce
1. Place triangle on the canvas.
2. Change border width to 2
3. Change size to min height and resize the width left/right

![image](https://cloud.githubusercontent.com/assets/668664/19520950/a63f343e-961a-11e6-8bd7-76472977c794.png)

**Comment by cliftonm** [comment]
Yeah, that's ugly, and points the bigger problems with how .NET renders shapes with pen widths > 1.  I'll look some more at this issue.  One thing I'm considering is that the display rectangle is shrunk by the pen width/2, so that the shape always renders inside the display rectangle, except that even that doesn't work in your scenario.  This may require a custom drawing routine for pen widths > 1 for all shapes.  Sigh.

**Comment by cliftonm** [comment]
![rtriangle](https://cloud.githubusercontent.com/assets/3474356/20610684/ebeaa402-b26a-11e6-961e-4997cac4fcaf.png)

The compromise.
