### ISSUE TITLE
The selected object should take priority for drag operations

### ISSUE THREAD

**Issue by qwertie** [cliftonm/FlowSharp#33]
I'm drawing a diagram with boxes nested inside other boxes. While trying to resize the outer box, if an inner box is nearby then FlowSharp tends to prefer to drag that object instead, even if the resize handles of the selected box are closer to the mouse!

**Comment by cliftonm** [comment]
I believe this issue has been corrected by a bug fix in the mouse controller.  Actually what I consider to be a bug in .NET's mouse event, in that a mouse click also produced a mouse-move event.  Because the mouse move event was initiating dragging the shape, rather than the anchor, I think this was the issue.  The mouse controller now ignores mouse move events when the mouse hasn't actually moved.  I recreated a test scenario with multiple nested boxes and everything worked correctly.

**Comment by qwertie** [comment]
What I'm talking about happens even before you click the mouse - the app shows before you click which object will be resized when you click and drag, and sometimes it's not the selected object that the mouse cursor is actually on, in case there's a nearby, nested shape.
